### ISSUE TITLE
rtcm32json struggles with some RTCM snippets from Australia

### ISSUE THREAD

**Issue by ljbade** [swift-nav/librtcm#68]
I have captured some snippets of RTCM I wanted to decode with rtcm32json but instead I get a large unparsed blob.

RTKLIB can decode the same file into RINEX observations without issues.

Here is one of the files:
[01NA7.zip](https://github.com/swift-nav/librtcm/files/2643057/01NA7.zip)

**Comment by ljbade** [comment]
I think it might have something to do with the messages in https://github.com/swift-nav/librtcm/blob/master/haskell/src/Data/RTCM3/Antennas.hs

The 1006, 1008, 1033 and 1230 messages are the only ones missing from the JSON compared to the live stream in RTKLIB.

**Comment by mfine** [comment]
Should be fixed now with latest.
